# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HHPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HHPlayerDemo
    pod 'Masonry', '1.1.0'
    
  
  target 'HHPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HHPlayerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
